language: cpp
compiler: gcc
dist: trusty


notifications:
  email: false

addons:
  apt:
    packages:
      - realpath wget git realpath

install:
  - sudo wget -c https://github.com/appimage-conan-community/conan-appimage/releases/download/continuous/conan-x86_64.AppImage -O /usr/local/bin/conan
  - sudo chmod a+x /usr/local/bin/conan
  - conan user
  - conan remote add appimage-conan-community https://api.bintray.com/conan/appimage-conan-community/public-conan --insert=0
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan --insert=1
  # Original cmake binaries are faulty forcing re-build
  - conan install cmake_installer/3.14.3@conan/stable --build cmake_installer

script:
  - conan install . --build missing -s compiler.libcxx=libstdc++11 -s compiler.cppstd=11
  - conan build .

after_success:
  - ls -lh
  # make sure only pushes to rewrite create a new release, otherwise pretend PR and upload to transfer.sh
  - if [ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ] && [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh appimage-services*.AppImage*
